<?php
	/**
	 * Activate Add-ons
	 * Here you can enter your activation codes to unlock Add-ons to use in your theme. 
	 * Since all activation codes are multi-site licenses, you are allowed to include your key in premium themes.
	 */
	function my_acf_settings( $options )
	{
	    // activate add-ons
	    $options["activation_codes"]["repeater"] = "QJF7-L4IX-UCNP-RF2W";
	    $options["activation_codes"]["options_page"] = "OPN8-FA4J-Y2LW-81LS";
	    $options["activation_codes"]["flexible_content"] = "FC9O-H6VN-E4CL-LT33";
	    $options["activation_codes"]["gallery"] = "GF72-8ME6-JS15-3PZC";
	    
		$options["options_page"]["title"] = "Theme Options";
	    
	    // setup other options (http://www.advancedcustomfields.com/docs/filters/acf_settings/)
	    return $options;
	    
	}
	add_filter("acf_settings", "my_acf_settings");

	add_action('acf/register_fields', 'my_register_fields');

	function my_register_fields()
	{
		
		include_once(get_template_directory() . '/admin/plugins/acf-repeater/repeater.php');
		include_once(get_template_directory() . '/admin/plugins/acf-gallery/gallery.php');
		include_once(get_template_directory() . '/admin/plugins/acf-flexible-content/flexible-content.php');
	}

	/**
	 *  Register Field Groups
	 *
	 *  The register_field_group function accepts 1 array which holds the relevant data to register a field group
	 *  You may edit the array as you see fit. However, this may result in errors if the array is not compatible with ACF
	 */

	if(function_exists("register_field_group"))
	{
		register_field_group(array (
			'id' => 'acf_portfolio-options',
			'title' => 'Portfolio Options',
			'fields' => array (
				array (
					'key' => 'field_52447846d2484',
					'label' => 'General Settings',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_524476ef3a75d',
					'label' => 'Portfolio Caption',
					'name' => 'portfolio_caption',
					'type' => 'text',
					'instructions' => 'Caption to be displayed in the header of portfolio page.',
					'default_value' => 'Take a look in the latest work from Cotton Company.',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5244777f11324',
					'label' => 'Posts per page',
					'name' => 'portfolio_posts_per_page',
					'type' => 'number',
					'instructions' => 'Number of portfolio posts to be displayed per page. To display all in the same page you should type -1.',
					'default_value' => 9,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array (
					'key' => 'field_5244783ad2483',
					'label' => 'Layout',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_52447859d2485',
					'label' => 'X-Small Device Columns',
					'name' => 'xsmall_device_columns',
					'type' => 'select',
					'instructions' => 'The number of columns you want to have for Portfolio in X-Small devices.',
					'choices' => array (
						6 => 6,
						12 => 12,
					),
					'default_value' => 12,
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_524479f3b2387',
					'label' => 'Small Device Columns',
					'name' => 'small_device_columns',
					'type' => 'select',
					'instructions' => 'The number of columns you want to have for Portfolio in Small devices.',
					'choices' => array (
						3 => 3,
						4 => 4,
						6 => 6,
						12 => 12,
					),
					'default_value' => 6,
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_52447a14b2388',
					'label' => 'Medium and Large Device Columns',
					'name' => 'medium_device_columns',
					'type' => 'select',
					'instructions' => 'The number of columns you want to have for Portfolio in Medium and Large devices.',
					'choices' => array (
						2 => 2,
						3 => 3,
						4 => 4,
						6 => 6,
						12 => 12,
					),
					'default_value' => 4,
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'page',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'template-portfolio.php',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_post-format-video',
			'title' => 'Post Format - Video',
			'fields' => array (
				array (
					'key' => 'field_52440d8046ca8',
					'label' => 'Video Source',
					'name' => 'video_source',
					'type' => 'select',
					'instructions' => 'Choose the source of your video file.',
					'choices' => array (
						'Link' => 'Link',
						'Upload' => 'Upload',
						'Youtube/Vimeo' => 'Youtube/Vimeo',
					),
					'default_value' => 'Link',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_52440e4e6665a',
					'label' => 'Upload Video File',
					'name' => 'upload_video_file',
					'type' => 'file',
					'instructions' => 'Upload for the video file.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '==',
								'value' => 'Upload',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Link',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Youtube/Vimeo',
							),
						),
						'allorany' => 'all',
					),
					'save_format' => 'url',
					'library' => 'all',
				),
				array (
					'key' => 'field_52440e9382b2f',
					'label' => 'Video File Link',
					'name' => 'video_file_link',
					'type' => 'text',
					'instructions' => 'Link for the video file.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '==',
								'value' => 'Link',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Upload',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Youtube/Vimeo',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_52440ddc46ca9',
					'label' => 'Poster',
					'name' => 'image_video',
					'type' => 'image',
					'instructions' => 'Image to be displayed before clicking on play video button. Make sure it has the same aspect ratio as the video.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Youtube/Vimeo',
							),
						),
						'allorany' => 'all',
					),
					'save_format' => 'url',
					'preview_size' => 'large',
					'library' => 'all',
				),
				array (
					'key' => 'field_52440ec685082',
					'label' => 'Youtube/Vimeo Url',
					'name' => 'youtube_vimeo_url',
					'type' => 'text',
					'instructions' => 'Place the url to display a video from youtube or vimeo.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '==',
								'value' => 'Youtube/Vimeo',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Link',
							),
							array (
								'field' => 'field_52440d8046ca8',
								'operator' => '!=',
								'value' => 'Upload',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'post_format',
						'operator' => '==',
						'value' => 'video',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_blog-options',
			'title' => 'Blog Options',
			'fields' => array (
				array (
					'key' => 'field_522dd964fc7c0',
					'label' => 'Caption',
					'name' => 'blog_caption',
					'type' => 'text',
					'instructions' => 'Caption to be displayed in the header of blog page.',
					'default_value' => 'Follow the latest news and thoughts from people at Cotton Company.',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_522dd996fc7c1',
					'label' => 'Posts per page',
					'name' => 'number_of_posts',
					'type' => 'number',
					'instructions' => 'Number of posts to be displayed per page. To display all in the same page you should type -1.',
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => -1,
					'max' => '',
					'step' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'page',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'template-blog.php',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_post-format-audio',
			'title' => 'Post Format - Audio',
			'fields' => array (
				array (
					'key' => 'field_5227de78b9285',
					'label' => 'File Source',
					'name' => 'file_source',
					'type' => 'select',
					'instructions' => 'Choose the source of your audio file.',
					'choices' => array (
						'Link' => 'Link',
						'Upload' => 'Upload',
					),
					'default_value' => 'Link',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_5227ddaaaab4c',
					'label' => 'Upload Audio File',
					'name' => 'upload_audio_file',
					'type' => 'file',
					'instructions' => 'Upload for the audio file.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5227de78b9285',
								'operator' => '==',
								'value' => 'Upload',
							),
							array (
								'field' => 'field_5227de78b9285',
								'operator' => '!=',
								'value' => 'Link',
							),
						),
						'allorany' => 'all',
					),
					'save_format' => 'url',
					'library' => 'all',
				),
				array (
					'key' => 'field_5227def710b21',
					'label' => 'Audio File Link',
					'name' => 'audio_file_link',
					'type' => 'text',
					'instructions' => 'Link for the audio file.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5227de78b9285',
								'operator' => '==',
								'value' => 'Link',
							),
							array (
								'field' => 'field_5227de78b9285',
								'operator' => '!=',
								'value' => 'Upload',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_522de8b0a1d53',
					'label' => 'Poster',
					'name' => 'image_audio',
					'type' => 'image',
					'instructions' => 'Image to be displayed behind the audio player and identify the post.',
					'required' => 1,
					'save_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'post_format',
						'operator' => '==',
						'value' => 'audio',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_post-format-link',
			'title' => 'Post Format - Link',
			'fields' => array (
				array (
					'key' => 'field_5227da095a07c',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'text',
					'instructions' => 'Link that you want to display as a post.',
					'default_value' => '',
					'placeholder' => 'www.awesomelink.com',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_522bea7cb975d',
					'label' => 'Header Image',
					'name' => 'link_image',
					'type' => 'image',
					'instructions' => 'If you want to put a picture related to the link on top of the post.',
					'save_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_format',
						'operator' => '==',
						'value' => 'link',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_post-format-gallery',
			'title' => 'Post Format - Gallery',
			'fields' => array (
				array (
					'key' => 'field_5227d948c0501',
					'label' => 'Images',
					'name' => 'gallery_images',
					'type' => 'gallery',
					'instructions' => 'Images that will be shown in your gallery post.',
					'preview_size' => 'medium',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_format',
						'operator' => '==',
						'value' => 'gallery',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_post-format-image',
			'title' => 'Post Format - Image',
			'fields' => array (
				array (
					'key' => 'field_522767283d886',
					'label' => 'Header Image',
					'name' => 'header_image',
					'type' => 'image',
					'instructions' => 'A full-width image to display on top inside the post.',
					'save_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 0,
					),
					array (
						'param' => 'post_format',
						'operator' => '==',
						'value' => 'image',
						'order_no' => 1,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_project-details',
			'title' => 'Project Details',
			'fields' => array (
				array (
					'key' => 'field_5224c929c2d7a',
					'label' => 'Client',
					'name' => 'client',
					'type' => 'text',
					'default_value' => 'To what/who you made ​​this site.',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_524423dc306cf',
					'label' => 'Header Type',
					'name' => 'header_type',
					'type' => 'select',
					'instructions' => 'Select if you want video or image to display in the header of project page.',
					'choices' => array (
						'Image' => 'Image',
						'Video' => 'Video',
					),
					'default_value' => '',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_5224c9e7c2d7c',
					'label' => 'Header Image',
					'name' => 'header_image',
					'type' => 'image',
					'instructions' => 'A full-width image to display on top inside the project.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_524423dc306cf',
								'operator' => '==',
								'value' => 'Image',
							),
							array (
								'field' => 'field_524423dc306cf',
								'operator' => '!=',
								'value' => 'Video',
							),
						),
						'allorany' => 'all',
					),
					'save_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array (
					'key' => 'field_52442456c052b',
					'label' => 'Header Video',
					'name' => 'header_video',
					'type' => 'text',
					'instructions' => 'Place the url to display a video from youtube or vimeo.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_524423dc306cf',
								'operator' => '==',
								'value' => 'Video',
							),
							array (
								'field' => 'field_524423dc306cf',
								'operator' => '!=',
								'value' => 'Image',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'portfolio',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_sections-options',
			'title' => 'Sections Options',
			'fields' => array (
				array (
					'key' => 'field_522cc91f3800d',
					'label' => 'Background Color',
					'name' => 'background-color',
					'type' => 'color_picker',
					'instructions' => 'Choose the background color for this section.',
					'default_value' => '#fff',
				),
				array (
					'key' => 'field_521fea828b6d9',
					'label' => 'Additional Options',
					'name' => 'additional_options',
					'type' => 'flexible_content',
					'layouts' => array (
						array (
							'label' => 'Blog',
							'name' => 'blog',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_52261123339d5',
									'label' => 'X-Small Device Columns',
									'name' => 'xsmall_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Blog in X-Small devices.',
									'column_width' => '',
									'choices' => array (
										6 => 6,
										12 => 12,
									),
									'default_value' => 12,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_52261123339d6',
									'label' => 'Small Device Columns',
									'name' => 'small_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Blog in Small devices.',
									'column_width' => '',
									'choices' => array (
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 6,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_52261123339d7',
									'label' => 'Medium and Large Device Columns',
									'name' => 'medium_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Blog in Medium and Large devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 4,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_522750d4ae673',
									'label' => 'Blog Page',
									'name' => 'blog_page',
									'type' => 'page_link',
									'instructions' => 'Select a Blog Page if you want a page to display all the blog posts.',
									'column_width' => '',
									'post_type' => array (
										0 => 'page',
									),
									'allow_null' => 1,
									'multiple' => 0,
								),
								array (
									'key' => 'field_52448e1b0ced6',
									'label' => 'Posts to display',
									'name' => 'posts_to_display',
									'type' => 'number',
									'instructions' => 'Number of blog posts you want to display.',
									'column_width' => '',
									'default_value' => 3,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
								),
							),
						),
						array (
							'label' => 'Contact',
							'name' => 'contact',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_523cc978e697d',
									'label' => 'Small, Medium and Large Device Columns',
									'name' => 'small_medium_large_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Contact Form in Small, Medium and Large devices.',
									'column_width' => '',
									'choices' => array (
										4 => 4,
										6 => 6,
										8 => 8,
										10 => 10,
										12 => 12,
									),
									'default_value' => 8,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_523c758729fbb',
									'label' => 'Email',
									'name' => 'email',
									'type' => 'text',
									'instructions' => 'Enter the email address where you\'d like to receive emails from the form, or leave blank to use admin email.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_523cd5c511895',
									'label' => 'Location',
									'name' => 'location',
									'type' => 'textarea',
									'instructions' => 'Where you work/live.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'formatting' => 'br',
								),
								array (
									'key' => 'field_523cda36d2ee0',
									'label' => 'Location Google Maps Link',
									'name' => 'location_link',
									'type' => 'text',
									'instructions' => 'The link for the location using Google Maps.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_523cd5c511894',
									'label' => 'Phone',
									'name' => 'phone',
									'type' => 'textarea',
									'instructions' => 'Enter other contact information, not only the email.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'formatting' => 'br',
								),
								array (
									'key' => 'field_523c745229fba',
									'label' => 'Success Message',
									'name' => 'success_message',
									'type' => 'text',
									'instructions' => 'Type the message you want to be displayed when form validates correctly and email is sent.',
									'column_width' => '',
									'default_value' => 'Thanks. We\'ll get back to you as soon as possible.',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5231f2170e483',
									'label' => 'Error Message',
									'name' => 'error_message',
									'type' => 'text',
									'instructions' => 'Type the message you want to be displayed when form fails to validate.',
									'column_width' => '',
									'default_value' => 'Please fill in all data correctly.',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
							),
						),
						array (
							'label' => 'Portfolio',
							'name' => 'portfolio',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_521ff817f98bb',
									'label' => 'X-Small Device Columns',
									'name' => 'xsmall_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Portfolio in X-Small devices.',
									'column_width' => '',
									'choices' => array (
										6 => 6,
										12 => 12,
									),
									'default_value' => 12,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521ff86af98bc',
									'label' => 'Small Device Columns',
									'name' => 'small_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Portfolio in Small devices.',
									'column_width' => '',
									'choices' => array (
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 6,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521ff8e5f98bd',
									'label' => 'Medium and Large Device Columns',
									'name' => 'medium_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Portfolio in Medium and Large devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 4,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521ff86af98be',
									'label' => 'Portfolio Page',
									'name' => 'portfolio_page',
									'type' => 'page_link',
									'instructions' => 'Select a Portfolio Page if you want a page to display all the blog posts.',
									'column_width' => '',
									'post_type' => array (
										0 => 'page',
									),
									'allow_null' => 1,
									'multiple' => 0,
								),
							),
						),
						array (
							'label' => 'Services',
							'name' => 'services',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_5224ba8acaaa6',
									'label' => 'X-Small Device Columns',
									'name' => 'xsmall_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Services in X-Small devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 3,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_5224bab9caaa8',
									'label' => 'Small Device Columns',
									'name' => 'small_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Services in Small devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 6,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_5224bab8caaa7',
									'label' => 'Medium and Large Device Columns',
									'name' => 'medium_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Services in Medium and Large devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 3,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_5224bb45caaa9',
									'label' => 'What you do',
									'name' => 'what_you_do',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5224bc24caaaa',
											'label' => 'Name',
											'name' => 'name',
											'type' => 'text',
											'instructions' => 'The service name.',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => 'Service Name',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5224bc3acaaab',
											'label' => 'Description',
											'name' => 'description',
											'type' => 'text',
											'instructions' => 'Short description of service.',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => 'Service Description',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5224bc57caaac',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => 'Image to display with your service.',
											'column_width' => '',
											'save_format' => 'url',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_5224bc6dcaaad',
											'label' => 'Skills',
											'name' => 'skills',
											'type' => 'repeater',
											'instructions' => 'Specific skills for this service.',
											'column_width' => '',
											'sub_fields' => array (
												array (
													'key' => 'field_5224bc84caaae',
													'label' => 'Name',
													'name' => 'name',
													'type' => 'text',
													'instructions' => 'The skill name.',
													'column_width' => 85,
													'default_value' => '',
													'placeholder' => 'Skill Name',
													'prepend' => '',
													'append' => '',
													'formatting' => 'html',
													'maxlength' => '',
												),
												array (
													'key' => 'field_5224bcafcaaaf',
													'label' => 'Percentage',
													'name' => 'percentage',
													'type' => 'number',
													'instructions' => 'The skill percentage in your service.',
													'column_width' => 15,
													'default_value' => '',
													'placeholder' => 50,
													'prepend' => '',
													'append' => '',
													'min' => 0,
													'max' => 100,
													'step' => '',
												),
											),
											'row_min' => 0,
											'row_limit' => '',
											'layout' => 'table',
											'button_label' => 'Add Skill',
										),
									),
									'row_min' => 0,
									'row_limit' => '',
									'layout' => 'row',
									'button_label' => 'Add Service',
								),
							),
						),
						array (
							'label' => 'Slider',
							'name' => 'slider',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_521fedf4e8004',
									'label' => 'Images',
									'name' => 'images',
									'type' => 'gallery',
									'column_width' => '',
									'preview_size' => 'thumbnail',
								),
							),
						),
						array (
							'label' => 'Social',
							'name' => 'social',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_5224bd2e68360',
									'label' => 'Flickr ID',
									'name' => 'flickrid',
									'type' => 'text',
									'instructions' => 'You can get your id from: http://idgettr.com/',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '36587311@N08',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5224bd4068361',
									'label' => 'Instagram Username',
									'name' => 'instagramUser',
									'type' => 'text',
									'instructions' => 'The Instagram username you want to get the feed from.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => 'alotofbradshaw',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5224bdba68362',
									'label' => 'Twitter Username',
									'name' => 'twitterUser',
									'type' => 'text',
									'instructions' => 'The Twitter username you want to get the feed from.',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => 'digitalcookers',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
							),
						),
						array (
							'label' => 'Team',
							'name' => 'team',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_521ff045f3b9f',
									'label' => 'X-Small Device Columns',
									'name' => 'xsmall_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Team in X-Small devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										12 => 12,
									),
									'default_value' => 6,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521ff0ccf3ba1',
									'label' => 'Small Device Columns',
									'name' => 'small_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Team in Small devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										'12:12' => '12:12',
									),
									'default_value' => 6,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521ff0caf3ba0',
									'label' => 'Medium and Large Device Columns',
									'name' => 'medium_device_columns',
									'type' => 'select',
									'instructions' => 'The number of columns you want to have for Team in Medium and Large devices.',
									'column_width' => '',
									'choices' => array (
										2 => 2,
										3 => 3,
										4 => 4,
										6 => 6,
										'12:12' => '12:12',
									),
									'default_value' => 3,
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_521fecb541889',
									'label' => 'Members',
									'name' => 'members',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_521fecc24188a',
											'label' => 'Name',
											'name' => 'name',
											'type' => 'text',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_521fed1b21c4b',
											'label' => 'Role',
											'name' => 'role',
											'type' => 'text',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_521fed2121c4c',
											'label' => 'Photo',
											'name' => 'photo',
											'type' => 'image',
											'column_width' => '',
											'save_format' => 'url',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_521fed3321c4d',
											'label' => 'Photo Hover',
											'name' => 'photo_hover',
											'type' => 'image',
											'column_width' => '',
											'save_format' => 'url',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_521fed3d21c4e',
											'label' => 'Social',
											'name' => 'social',
											'type' => 'repeater',
											'column_width' => '',
											'sub_fields' => array (
												array (
													'key' => 'field_521fed4621c4f',
													'label' => 'Media',
													'name' => 'media',
													'type' => 'select',
													'column_width' => 30,
													'choices' => array (
														'Twitter' => 'Twitter',
														'Facebook' => 'Facebook',
														'Linkedin' => 'Linkedin',
														'Google-Plus' => 'Google-Plus',
													),
													'default_value' => '',
													'allow_null' => 0,
													'multiple' => 0,
												),
												array (
													'key' => 'field_521fed6a21c50',
													'label' => 'Link',
													'name' => 'link',
													'type' => 'text',
													'column_width' => 70,
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'formatting' => 'html',
													'maxlength' => '',
												),
											),
											'row_min' => 0,
											'row_limit' => '',
											'layout' => 'table',
											'button_label' => 'Add Social Media',
										),
									),
									'row_min' => 0,
									'row_limit' => '',
									'layout' => 'row',
									'button_label' => 'Add Member',
								),
							),
						),
					),
					'button_label' => 'Add Options',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'sections',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
	}
